spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kursaplikacji?useUnicode=true&serverTimezone=UTC
    username: root
    password: 1234
  liquibase:
    change-log: classpath:liquibase-changelog.xml
server:
  error:
    include-message: always
    include-binding-errors: always