spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kursaplikacji?useUnicode=true&serverTimezone=UTC
    username: root
    password: 1234
  liquibase:
    change-log: classpath:liquibase-changelog.xml
  jpa:
    show-sql: true
server:
  error:
    include-message: always
    include-binding-errors: always

app:
  uploadDir: ./data/productImages/
  cart:
    cleanup:
      expression: "0 0 3 * * *"